# Independent settings for the planner's costmap
global_costmap:
  plugins:
    - name: static_layer
      type: 'costmap_2d::StaticLayer'
    - name: obstacle_laser_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: obstacle_rgbd_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'
    - name: proxemic_layer
      type: 'social_navigation_layers::ProxemicLayer'
    - name: passing_layer
      type: 'social_navigation_layers::PassingLayer'
