base_local_planner: robotino_local_planner/RobotinoLocalPlanner

RobotinoLocalPlanner:
  heading_lookahead: 1.0
  num_window_points: 10

  max_linear_vel: 0.55
  min_linear_vel: 0.1

  max_rotation_vel: !degrees 60.0
  min_rotation_vel: !degrees 23.0

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: !degrees 11.5
