# Parameters file based on:
# https://github.com/rayvburn/drl_local_planner_ros_stable_baselines/blob/melodic-devel/rl_bringup/config/rl_params_common.yaml

###################################
# robot parameters                #
###################################
robot_frame: base_footprint
max_vel_x: 0.5
max_vel_th: 1.05
xy_goal_tolerance: 0.2

###################################
# planner parameters              #
###################################
num_of_wps: 8
look_ahead_distance: 0.5
wp_reached_dist: 0.2

###################################
# RL agent parameters             #
###################################
update_frequency: 10

# the value used during training, corresponds to `rew_fnc` in the `entrypoint_ppo2.sh`
rew_fnc: 19

# State representation - image
# number of height cells in positive direction
img_width_pos: 70
# number of height cells in negative direction
img_width_neg: 20
# number of height cells in negative direction
img_height: 70
# resolution in m/cell
resolution: 0.15

# State representation - laser scan
# this must be equal to the number of laser samples used during the policy training
scan_size: 90
# scan is discretized to a resolution
resolution: 0.05

###################################
# topics                          #
###################################
# NOTE: if a topic does not start with the "/", it will be automatically placed within the node's namespace (unless
# the global namespace is requested)
state_image_generation_srv_name: rl_agent/image_generator/get_image
merge_scans_srv_name: rl_agent/merge_scans

action_topic: rl_agent/action
done_topic: rl_agent/done
trigger_agent_topic: rl_agent/trigger_agent
wp_generator_path_srv: rl_agent/wp_generator/set_global_plan
waypoint_topic: rl_agent/wp

map_topic: /map
