base_local_planner: eband_local_planner/EBandPlannerROS

EBandPlannerROS:
  Ctrl_Rate : 10
  differential_drive: True
  max_acceleration: 1.0
  max_vel_lin: 0.5
  max_vel_th: !degrees 60.0
  min_vel_lin: -0.1
  min_vel_th: !degrees 23.0
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: !degrees 11.5
