# Parameters placed here overwrite default values from dynamic reconfigure
base_local_planner: hubero_local_planner/HuberoPlannerROS

# related to LatchedStopRotateController (helper)
# This is mandatory to avoid ignoring goals that have similar orientation to the previous goal
latch_xy_goal_tolerance: false

controller_frequency: 4.0

HuberoPlannerROS:
  # NOTE: extended costmap_converter plugin is used here
  costmap_converter_plugin: "costmap_converter::CostmapToSegmentedPolygonsDBSMCCH"
  costmap_converter_rate: 2.0
  costmap_converter_spin_thread: true
  costmap_converter:
    # basic CC section remains default, see below
    # CostmapToPolygonsDBSMCCH:
      # original costmap_converter plugin parameters with values go here...
    CostmapToSegmentedPolygonsDBSMCCHSODR:
      # Distance adjusted to reduce number of obstacles - cluster them together
      segmentation_distance: 0.125

  # Robot footprint
  is_footprint_dynamic: true
  footprint_model:
    type: "circular"
    radius: 0.275

  # Local Planner limits
  max_vel_trans: 1.00
  max_vel_x: 1.00
  # Social trajectory generator performs way better when it has possibility to move backward slightly.
  # Ensures faster positioning at goal position.
  min_vel_x: -0.1
  min_vel_theta: 0.3
  # TIAGo has non-holonomic drive
  min_vel_y: 0.0
  max_vel_y: 0.0

  # disabling `prune_plan` will likely break `INITIATE_EXECUTION` behaviour, keep this default
  prune_plan: true

  # other than that use default from dynamic reconfigure
