# Parameters placed here overwrite default values from dynamic reconfigure
base_local_planner: hubero_local_planner/HuberoPlannerROS

# related to LatchedStopRotateController (helper)
# This is mandatory to avoid ignoring goals that have similar orientation to the previous goal
latch_xy_goal_tolerance: false

controller_frequency: 4.0

HuberoPlannerROS:
  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
  costmap_converter_rate: 2.0
  costmap_converter_spin_thread: true

  # Robot footprint
  is_footprint_dynamic: true
  footprint_model:
    type: "circular"
    radius: 0.275

  # Local Planner limits
  max_vel_trans: 0.5
  max_vel_x: 0.5
  max_vel_theta: !degrees 60.0
  min_vel_theta: !degrees 23.0
  acc_lim_x: 1.0
  acc_lim_theta: !degrees 60.0
  acc_lim_trans: 1.0

  trans_stopped_vel: 0.1
  theta_stopped_vel: !degrees 6.0

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: !degrees 11.5

  # Social trajectory generator performs way better when it has possibility to move backward slightly.
  # Ensures faster positioning at goal position.
  min_vel_x: -0.1
  min_vel_theta: 0.3
  # TIAGo has non-holonomic drive
  min_vel_y: 0.0
  max_vel_y: 0.0
  acc_lim_y: 0.0

  # disabling `prune_plan` will likely break `INITIATE_EXECUTION` behaviour, keep this default
  prune_plan: true

  # other than that use default from dynamic reconfigure
