# Parameters placed here overwrite default values from dynamic reconfigure
base_local_planner: hubero_local_planner/HuberoPlannerROS

HuberoPlannerROS:
  # Robot footprint
  is_footprint_dynamic: true
  footprint_model:
    type: "circular"
    radius: 0.275

  # Local Planner limits
  max_vel_trans: 1.00
  max_vel_x: 1.00
  # Social trajectory generator performs way better when it has possibility to move backward slightly.
  # Ensures faster positioning at goal position.
  min_vel_x: -0.1
  min_vel_theta: 0.3
  # other than that use default from dynamic reconfigure
