# Original configuration reference:
# https://github.com/makokal/socially_normative_navigation/tree/master/snn_launchers/config/behavior_parameters
# Paper:
# Okal, Arras: "Learning Socially Normative Robot Navigation Behaviors using Bayesian Inverse Reinforcement Learning"

# Originally - hallway and intersection scenes
flow_behavior_layer:
    behavior_name: 'merge'
    # behavior_params_merge: [1.04, 2.750005, 0.02] # original - hallway scene
    # behavior_params_merge: [0.0, 2.750005, 0.02] # original - intersection scene
    behavior_params_merge: [1.04, 2.750005, 0.02] # modified
    behavior_params_nomerge: [0.0, 0.0, 0.02]

# Originally - lobby scene
#
# Learned parameters for lobby navigation
# Behaviors are: 'polite', 'sociable' and 'rude'
social_compliance_layer:
    behavior_name: 'polite'
    behavior_params_polite: [2.0000129, 1.350002, 0.002]
    behavior_params_sociable: [1.00023, 0.25, 0.5]
    behavior_params_rude: [0.0, 0.0, 0.5]
